USE buroKadrov;

CREATE TABLE Speciality
(
	ID INT NOT NULL IDENTITY,
	Speciality_name VARCHAR(30) NOT NULL,
	Salary SMALLMONEY NOT NULL

	CONSTRAINT PK_Speciality_ID PRIMARY KEY (ID)
)

CREATE TABLE Workers
(
	ID INT NOT NULL IDENTITY,
	Worker_name VARCHAR(50) NOT NULL,
	Birthday DATE NOT NULL,
	Age INT NOT NULL,
	Speciality_ID INT NOT NULL,

	CONSTRAINT PK_Worker_ID PRIMARY KEY (ID),
	CONSTRAINT FK_Worker_Speciality FOREIGN KEY (Speciality_ID) REFERENCES  Speciality(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
)

CREATE TABLE Directors
(
	ID INT NOT NULL IDENTITY,
	Director_name VARCHAR(30) NOT NULL,
	Birthday DATE NOT NULL,

	CONSTRAINT PK_Director_ID PRIMARY KEY (ID)
)

CREATE TABLE Companies
(
	ID INT NOT NULL IDENTITY,
	Company_name VARCHAR(30) NOT NULL,
	Base_date DATE NOT NULL,
	Director_ID INT NOT NULL,

	CONSTRAINT PK_Company_ID PRIMARY KEY (ID),
	CONSTRAINT FK_Companys_Director FOREIGN KEY (Director_ID) REFERENCES Directors(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
)

CREATE TABLE Employees
(
	ID INT NOT NULL IDENTITY,
	Employee_name VARCHAR(30) NOT NULL,
	Birthday DATE NOT NULL,
	Contract_number INT NOT NULL,

	CONSTRAINT PK_Employee_ID PRIMARY KEY (ID)
)

CREATE TABLE Offences
(
	ID INT NOT NULL IDENTITY,
	Offence_name VARCHAR(30) NOT NULL,
	Punishment VARCHAR(30) NOT NULL 

	CONSTRAINT PK_Offence_ID PRIMARY KEY (ID)
)

CREATE TABLE Encouragements
(
	ID INT NOT NULL IDENTITY,
	Encouragement_name VARCHAR(30) NOT NULL

	CONSTRAINT PK_Encouragement_ID PRIMARY KEY (ID)
)

CREATE TABLE Workers_telephones
(
	ID INT NOT NULL IDENTITY,
	Telephone_number VARCHAR(30) NOT NULL,
	Telephone_type VARCHAR(30),
	Worker_ID INT NOT NULL,

	CONSTRAINT PK_Telephone_ID PRIMARY KEY (ID),
	CONSTRAINT FK_Worker_Telephone FOREIGN KEY (Worker_ID) REFERENCES Workers(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
)

CREATE TABLE Workers_encouragement
(
	Encouragement_ID INT NOT NULL,
	Worker_ID INT NOT NULL,
	
	CONSTRAINT FK_Encouragement_ID FOREIGN KEY (Encouragement_ID) REFERENCES Encouragements(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	CONSTRAINT FK_Workers_encouragement_ID FOREIGN KEY (Worker_ID) REFERENCES Workers(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
)

CREATE TABLE Workers_offences
(
	Offence_ID INT NOT NULL,
	Worker_ID INT NOT NULL,

	CONSTRAINT FK_Offence_ID FOREIGN KEY (Offence_ID) REFERENCES Offences(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	CONSTRAINT FK_Workers_offence_ID FOREIGN KEY (Worker_ID) REFERENCES Workers(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
)

CREATE TABLE Workers_company
(
	Company_ID INT NOT NULL,
	Worker_ID INT NOT NULL,

	CONSTRAINT FK_Company_ID FOREIGN KEY (Company_ID) REFERENCES Companies(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	CONSTRAINT FK_Workers_company_ID FOREIGN KEY (Worker_ID) REFERENCES Workers(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
)